#!/bin/bash
#SBATCH --partition=gpu_h100
#SBATCH --job-name=grmoe
#SBATCH --gpus=4
#SBATCH --cpus-per-task=4
#SBATCH --ntasks-per-node=8
#SBATCH --nodes=1
#SBATCH --time=22:59:59
#SBATCH --output=moe-llava_output_%A.out
#SBATCH --error=moe-llava_output_%A.err

SCRATCH_DIR="/scratch-shared/$USER"
MOE_LLAVA_DIR="$SCRATCH_DIR/moe-llava"
IMAGE_FOLDER="$MOE_LLAVA_DIR/images"
JSON_FOLDER="$MOE_LLAVA_DIR/train_json"
CHECKPOINT_DIR=$MOE_LLAVA_DIR/checkpoints

# Activate your environment
module purge
module load 2023
module load Anaconda3/2023.07-2

cd /home/fshi/MoE-LLaVA
source activate moellava

nvidia-smi
which deepspeed
deepspeed moellava/train/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path microsoft/phi-2 \
    --version plain \
    --data_path ${JSON_FOLDER}/llava_image_.json \
    --image_folder ${IMAGE_FOLDER} \
    --image_tower openai/clip-vit-large-patch14-336 \
    --image_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ${CHECKPOINT_DIR}/llavaphi-2.7b-pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 8 \
    --lazy_preprocess True \
    --report_to tensorboard \
    --cache_dir "./cache_dir"